# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zhang/Desktop/manage_ip/ila_8_16384_1120/ila_8_16384_1120.xci
# IP: The module: 'ila_8_16384_1120' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Desktop/manage_ip/ila_8_16384_1120/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_8_16384_1120'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/Desktop/manage_ip/ila_8_16384_1120/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_8_16384_1120'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/Desktop/manage_ip/ila_8_16384_1120/ila_8_16384_1120_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_8_16384_1120'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/zhang/Desktop/manage_ip/ila_8_16384_1120/ila_8_16384_1120.xci
# IP: The module: 'ila_8_16384_1120' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Desktop/manage_ip/ila_8_16384_1120/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_8_16384_1120'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/Desktop/manage_ip/ila_8_16384_1120/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_8_16384_1120'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/Desktop/manage_ip/ila_8_16384_1120/ila_8_16384_1120_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_8_16384_1120'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
