# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zhang/Desktop/manage_ip/flag_insert0_ram/flag_insert0_ram.xci
# IP: The module: 'flag_insert0_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Desktop/manage_ip/flag_insert0_ram/flag_insert0_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flag_insert0_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/zhang/Desktop/manage_ip/flag_insert0_ram/flag_insert0_ram.xci
# IP: The module: 'flag_insert0_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Desktop/manage_ip/flag_insert0_ram/flag_insert0_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flag_insert0_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
