# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zhang/manage_ip/pll_200/pll_200.xci
# IP: The module: 'pll_200' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/manage_ip/pll_200/pll_200_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_200'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/manage_ip/pll_200/pll_200.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/manage_ip/pll_200/pll_200_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/zhang/manage_ip/pll_200/pll_200.xci
# IP: The module: 'pll_200' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/manage_ip/pll_200/pll_200_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/manage_ip/pll_200/pll_200.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/manage_ip/pll_200/pll_200_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
