# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zhang/Desktop/manage_ip/hdlc_rx_ram/hdlc_rx_ram.xci
# IP: The module: 'hdlc_rx_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Desktop/manage_ip/hdlc_rx_ram/hdlc_rx_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdlc_rx_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/zhang/Desktop/manage_ip/hdlc_rx_ram/hdlc_rx_ram.xci
# IP: The module: 'hdlc_rx_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Desktop/manage_ip/hdlc_rx_ram/hdlc_rx_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdlc_rx_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
