# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zhang/Desktop/manage_ip/clk_pn_100_25/clk_pn_100_25.xci
# IP: The module: 'clk_pn_100_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Desktop/manage_ip/clk_pn_100_25/clk_pn_100_25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pn_100_25'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/Desktop/manage_ip/clk_pn_100_25/clk_pn_100_25.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pn_100_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/Desktop/manage_ip/clk_pn_100_25/clk_pn_100_25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pn_100_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/zhang/Desktop/manage_ip/clk_pn_100_25/clk_pn_100_25.xci
# IP: The module: 'clk_pn_100_25' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhang/Desktop/manage_ip/clk_pn_100_25/clk_pn_100_25_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pn_100_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/Desktop/manage_ip/clk_pn_100_25/clk_pn_100_25.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pn_100_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/zhang/Desktop/manage_ip/clk_pn_100_25/clk_pn_100_25_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pn_100_25'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
